; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Fri Aug 12 2022 09:47:47 GMT+0200 (Central European Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


