; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Fri Aug 12 2022 09:47:48 GMT+0200 (Central European Summer Time)

