; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.12 on Fri Aug 12 2022 09:47:48 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

